# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170830_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
