# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:39
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170916_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
