# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:41
from __future__ import unicode_literals

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20171113_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=courses.fields.PositionField(default=-1),
        ),
    ]
