# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My Courses', 'verbose_name_plural': 'My Courses'},
        ),
    ]
